// <auto-generated />
using System;
using Mechanics.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mechanics.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502053556_AddServiceRole")]
    partial class AddServiceRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Mechanics")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mechanics.Domain.Auth.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", "Mechanics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2afde195-550b-498e-a63d-7a6d556b25ba"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("a1097867-aa3e-416c-8685-190516b62a12"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ATTENDANT"
                        },
                        new
                        {
                            Id = new Guid("f6027484-89a4-49f6-a9cb-4d1733c2bab7"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MECHANIC"
                        },
                        new
                        {
                            Id = new Guid("f61b4ae9-cc8f-4fda-a39f-f70bb3c0840f"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CUSTOMER_USER"
                        },
                        new
                        {
                            Id = new Guid("f31bca41-0895-4af5-976f-ac892f833b1b"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CUSTOMER_ADMIN"
                        },
                        new
                        {
                            Id = new Guid("aaccfd08-66b2-473a-a0a1-2aa7fbbed7cc"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SERVICE"
                        });
                });

            modelBuilder.Entity("Mechanics.Domain.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CpfNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CpfNumber")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FullName");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", "Mechanics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db27b85d-b0f3-4300-bb45-7841f0d11617"),
                            CpfNumber = "12345678909",
                            CreationDate = new DateTime(2025, 10, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "administrator@mechanics.com",
                            FullName = "Administrator User",
                            PasswordHash = "AQAAAAIAAYagAAAAEPGF9Xsz+ARiCopDgQbQ8gbGubN6bhvNhpKiy8XK2BORE5eV95VywrM9rVE48i2m8w==",
                            RoleId = new Guid("2afde195-550b-498e-a63d-7a6d556b25ba"),
                            SecurityStamp = "efcaaf76-0535-45fc-a79c-06ab92c064bb"
                        },
                        new
                        {
                            Id = new Guid("c2a83e5a-27c7-440a-97e3-86234eebb3c7"),
                            CpfNumber = "98765432100",
                            CreationDate = new DateTime(2025, 10, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "attendant@mechanics.com",
                            FullName = "Attendant User",
                            PasswordHash = "AQAAAAIAAYagAAAAEEo/VptbCYVPiVkoEVHthpWAZUvV/KJ0WJkg+wKbtXJkmMHmSfnpFT4JTLofugBwyQ==",
                            RoleId = new Guid("a1097867-aa3e-416c-8685-190516b62a12"),
                            SecurityStamp = "370c4d16-8e11-46ca-9004-e1fb9311e49e"
                        },
                        new
                        {
                            Id = new Guid("4c3b8777-6c4a-4bf3-8ad5-aad48981f7f2"),
                            CpfNumber = "11144477735",
                            CreationDate = new DateTime(2025, 10, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mechanic@mechanics.com",
                            FullName = "Mechanic User",
                            PasswordHash = "AQAAAAIAAYagAAAAEKSeHdHtCfN38pakeil4oyEL0d07GBEySe6csY8jmXIKT3oEZVcZR7Jngd9qxFgmkQ==",
                            RoleId = new Guid("f6027484-89a4-49f6-a9cb-4d1733c2bab7"),
                            SecurityStamp = "0a3bc211-1220-4d20-80e9-bd850d0dc200"
                        });
                });

            modelBuilder.Entity("Mechanics.Domain.Auth.User", b =>
                {
                    b.HasOne("Mechanics.Domain.Auth.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
